version: "3.8"

services:
   server:
      build:
         context: .
      ports:
         - 9000:9000
      volumes:
         - .:/app # This will map the entire project directory to /app in the container
      environment:
         - DEBUG=True
