# Generated by Django 5.1.6 on 2025-02-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomBooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
